### ISSUE TITLE
macOS: delete coredumps after we upload them?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/coreupload-buildkite-plugin#11]
On macOS, AFAICT, Seatbelt doesn't clean up `/cores` at the end of each job. So, IIUC, this means that if we upload all of the coredumps in the `/cores` directory at the end of a job, we are not only uploading the coredumps from the current job, but also from previous jobs.

So, on macOS, at the end of a job, after we have uploaded the coredumps, should we do `rm -rf /cores/*` or something like that? That way, each job will only upload the coredumps from the current job.

**Comment by DilumAluthge** [comment]
cc: @staticfloat @Keno

**Comment by staticfloat** [comment]
We use the build directory to write out our core files.
